// Tests the distribution generated by Java's Math.random() function.

public class TestRandom {
	public static void main(String[] args) {
		double[] counters = { 0, 0 };
		int limit = Integer.parseInt(args[0]);
		for (int i = 0; i < limit; i++) {
			double rand = Math.random();
			int index = (int) (rand * 2);
			counters[index]++;
		}
		
		System.out.printf("> 0.5: %d times\n", (int) counters[1]);
		System.out.printf("<= 0.5: %d times\n", (int) counters[0]);

		if (counters[0] > 0 && counters[1] > 0) {
			double ratio = counters[1] / counters[0];
			System.out.println("Ratio: " + ratio);
		}
	}
}
